cat<<EOF >pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
    - name: log-generator
      image: your-dockerhub-username/log-generator:latest
      env:
        - name: LOG_DURATION
          value: "300000"  # 5 minutes in milliseconds
EOF